### ISSUE TITLE
It does not work with v2ray...

### ISSUE THREAD

**Issue by ayton** [Yuk1n0/Shadowsocks-Install#5]
Hi, thanks for the script...
When installing ss-libev without v2ray, it works fine, it does not work with v2ray, and the qr code after installing ss-libev+v2ray contains only ss-libev settings, there are no v2ray plugin settings.
1. I have domain
2. Im used port 443
3. Everything else is the default of your script
4. Installing the script without errors

**Comment by Yuk1n0** [comment]
Sorry for my late reply, because I have too much work these days.

The reason for this bug is that I neglected to generate the qrcode when adding v2ray-plugin function.I have fixed this bug in script.

By the way, if you are using Shadowrocket on iOS, qrcode seems incompatible.Shadowrocket uses its own encoding format.
